version: '3.7'

services:

  base:
    build:
      context: .
      args:
          LINK_YOUTUBE: https://www.youtube.com/watch?v=CzC2NRYaGAY
          NOISE: -15dB
          NOISE_D: 0.5
          # LINK_YOUTUBE: https://www.youtube.com/watch?v=noKzDrxHioc
    volumes:
      - ./out:/app/data