version: '3.7'

services:

  base:
    build:
      context: .
      args:
          LINK_YOUTUBE: https://www.youtube.com/watch?v=tpb8YPl11aI # trio e caiçara
          # LINK_YOUTUBE: https://www.youtube.com/watch?v=swFIjowXj60 # engole o choro
          # LINK_YOUTUBE: https://www.youtube.com/watch?v=CzC2NRYaGAY # trio
          NOISE: -20dB
          NOISE_D: 0.5
    volumes:
      - ./out:/app/data

  mp4:
    build:
      context: .
      dockerfile: ./mp4.dockerfile
      args:
          LINK_YOUTUBE: https://www.youtube.com/watch?v=tpb8YPl11aI # trio e caiçara
          # LINK_YOUTUBE: https://www.youtube.com/watch?v=swFIjowXj60 # engole o choro
          # LINK_YOUTUBE: https://www.youtube.com/watch?v=CzC2NRYaGAY # trio
          NOISE: -20dB
          NOISE_D: 0.5
    volumes:
      - ./mp4:/app/data