version: '3.7'

services:

  app:
    build:
      context: .
      args:
          LINK_YOUTUBE: https://www.youtube.com/watch?v=CzC2NRYaGAY
          NOISE: -20dB
          NOISE_D: 0.5
    volumes:
      - ./out:/app/data