version: '3.7'

services:

  base:
    build:
      context: .
      args:
          # LINK_YOUTUBE: https://www.youtube.com/watch?v=CzC2NRYaGAY
          LINK_YOUTUBE: https://www.youtube.com/watch?v=noKzDrxHioc
    environment:
      - NOISE=-30dB
      - NOISE_D=0.5
    volumes:
      - ./out:/app/data