version: '3.7'

services:

  app:
    build:
      context: .
    environment:
      LINK_YOUTUBE: https://www.youtube.com/watch?v=CzC2NRYaGAY
      # LINK_YOUTUBE: https://www.youtube.com/watch?v=MbLirwiFe9I
      NOISE: -30dB
      NOISE_D: 0.5
    volumes:
      - ./out:/app/data